In [2]:
import seq2seq_model
import pandas as pd

df = pd.read_csv('Data/1.csv', index_col=0)

2023-04-21 08:00:38.580874: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
train = df.to_numpy()

In [4]:
print(train)

[[0.58231363 0.00475988 0.04343497 0.02802144 0.10439447]
 [0.58232276 0.00471446 0.04335703 0.02804603 0.10594181]
 [0.5823319  0.00477049 0.04323389 0.02791067 0.10733656]
 ...
 [0.0099505  1.59753271 0.20620843 0.02734658 0.70877041]
 [0.0099505  1.59707288 0.20620843 0.02777458 0.71062442]
 [0.0099505  1.5966721  0.20620843 0.0282024  0.71285167]]


In [5]:
train_in, train_out = seq2seq_model.truncate(train)

In [6]:
print(train_in)
print(train_out)

[[[0.58231363 0.00475988 0.04343497 0.02802144 0.10439447]
  [0.58232276 0.00471446 0.04335703 0.02804603 0.10594181]
  [0.5823319  0.00477049 0.04323389 0.02791067 0.10733656]
  ...
  [0.60234197 0.01894496 0.41299725 0.04015485 0.34362679]
  [0.60229118 0.01893531 0.41149499 0.04001595 0.34499514]
  [0.60224039 0.01890412 0.41000123 0.03987036 0.34620833]]

 [[0.58232276 0.00471446 0.04335703 0.02804603 0.10594181]
  [0.5823319  0.00477049 0.04323389 0.02791067 0.10733656]
  [0.58234104 0.00492324 0.04307196 0.027702   0.10856802]
  ...
  [0.60229118 0.01893531 0.41149499 0.04001595 0.34499514]
  [0.60224039 0.01890412 0.41000123 0.03987036 0.34620833]
  [0.6021896  0.0188514  0.40848504 0.03971808 0.3472757 ]]

 [[0.5823319  0.00477049 0.04323389 0.02791067 0.10733656]
  [0.58234104 0.00492324 0.04307196 0.027702   0.10856802]
  [0.58235018 0.00516832 0.04287422 0.02768628 0.10963326]
  ...
  [0.60224039 0.01890412 0.41000123 0.03987036 0.34620833]
  [0.6021896  0.0188514  0.4084850